version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .
    stdin_open: true   # Keeps stdin open for interactive input
    tty: true          # Allocates a pseudo-TTY for the container

  # db is is db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always