@startuml
'https://plantuml.com/use-case-diagram

:organisation: as User

rectangle Database

usecase UC1 as "Get a list
of all the cities in a district
organised by largest population to smallest"

usecase Use as "Generate report"

usecase Display as "Display report"

User -> UC1
UC1 --> Use
Use - Database
Use --> Display

@enduml