name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
        #setting up a docker network so it works
      - name: Setup network
        run: |
            docker network create --driver bridge group-project
      - name: Build with Maven
        run: mvn package
      - name: Build
        #running the docker container and image
        run: docker build -t group_methods .
      - name: Run image
        run: docker run --network group-project --name groupcontainer group_methods
      - name: view logs
        run: docker logs groupcontainer
