name: A workflow for SEM Group 25 Project
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
        #setting up a docker network so it works
      - name: Build with Maven
        run: mvn package
      - name: Run docker compose
        run: docker compose up --abort-on-container-exit